bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '100000': 'KES100,000',
    '200000': 'KES200,000',
    '300000': 'KES300,000',
    '400000': 'KES400,000',
    '500000': 'KES500,000',
    '600000': 'KES600,000',
    '700000': 'KES700,000',
    '800000': 'KES800,000',
    '900000': 'KES900,000',
    '1000000': 'KES1M+',
}

state_choices = {
    'BAR': 'Baringo',
    'BMT': 'Bomet',
    'BGM': 'Bungoma',
    'BSA': 'Busia',
    'EGM': 'Elgeyo Marakwet',
    'EBU': 'Embu',
    'GSA': 'Garissa',
    'HMA': 'Homa Bay',
    'ISL': 'Isiolo',
    'KAJ': 'Kajiado',
    'KAK': 'Kakamega',
    'KCO': 'Kericho',
    'KBU': 'Kiambu',
    'KLF': 'Kilifi',
    'KIR': 'Kirinyaga',
    'KSI': 'Kisii',
    'KSM': 'Kisumu',
    'KTU': 'Kitui',
    'KLE': 'Kwale',
    'LKP': 'Laikipia',
    'LAU': 'Lamu',
    'MCS': 'Machakos',
    'MUE': 'Makueni',
    'MDA': 'Mandera',
    'MAR': 'Marsabit',
    'MRU': 'Meru',
    'MIG': 'Migori',
    'MSA': 'Mombasa',
    'MRA': "Murang'a",
    'NBO': 'Nairobi',
    'NKU': 'Nakuru',
    'NDI': 'Nandi',
    'NRK': 'Narok',
    'NYI': 'Nyamira',
    'NDR': 'Nyandarua',
    'NER': 'Nyeri',
    'SMB': 'Samburu',
    'SYA': 'Siaya',
    'TVT': 'Taita Taveta',
    'TAN': 'Tana River',
    'TNT': 'Tharaka Nithi',
    'TRN': 'Trans Nzoia',
    'TUR': 'Turkana',
    'USG': 'Uasin Gishu',
    'VHG': 'Vihiga',
    'WJR': 'Wajir',
    'PKT': 'West Pokot'
}
